# Generated by Django 4.0.6 on 2022-11-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_answer_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='quiz_question_answers',
        ),
        migrations.AlterModelTable(
            name='question',
            table='quiz_questions',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quizzes',
        ),
    ]
