# Generated by Django 4.0.6 on 2022-08-04 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quizzes_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
