# Generated by Django 4.0.6 on 2022-08-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0002_alter_user_managers_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
