# Generated by Django 4.0.6 on 2022-08-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0003_alter_quiz_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
