# Generated by Django 4.0.6 on 2022-08-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0005_move_quiz_table_to_app'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
